save_loc: "./results/casper/1213/unet_ddp"
seed: 1000

data:
    variables: ['U','V','T','Q']
    surface_variables: ['SP','t2m','V500','U500','T500','Z500','Q500']
    save_loc: '/glade/campaign/cisl/aiml/wchapman/MLWPS/STAGING/TOTAL_*'
    mean_path: '/glade/campaign/cisl/aiml/wchapman/MLWPS/STAGING/All_2010_staged.SLO.mean.nc'
    std_path: '/glade/campaign/cisl/aiml/wchapman/MLWPS/STAGING/All_2010_staged.SLO.std.nc'
    history_len: 6
    forecast_len: 7
    time_step: 1
    
trainer:
    mode: none # none, ddp, fsdp
    train_batch_size: 2
    valid_batch_size: 4
    batches_per_epoch: 500 # Set to 0 to use len(dataloader)
    valid_batches_per_epoch: 100
    learning_rate: 5.0e-04
    weight_decay: 1.0e-05
    start_epoch: 0
    epochs: 100
    amp: False
    grad_accum_every: 1
    apply_grad_penalty: False
    grad_max_norm: 1.0
    thread_workers: 4
    stopping_patience: 50
    teacher_forcing_ratio: 0.5

model:
    image_height: 640
    image_width: 1280
    frames: 15
    channels: 4
    surface_channels: 7
    dim: 1024
    rk4_integration: False
    use_visual_ssl: False
    visual_ssl_weight: 0.0
    use_codebook: False
    vq_codebook_dim: 16
    vq_codebook_size: 256
    vq_decay: 0.8
    vq_commitment_weight: 1.0
    use_vgg: False
    use_spectral_loss: True
    spectral_wavenum_init: 30
    spectral_lambda_reg: 0.8
    l2_recon_loss: True
    use_weights: False
    
weights:
    U: [0.132, 0.123, 0.113, 0.104, 0.095, 0.085, 0.076, 0.067, 0.057, 0.048, 0.039, 0.029, 0.02 , 0.011, 0.005]
    V: [0.132, 0.123, 0.113, 0.104, 0.095, 0.085, 0.076, 0.067, 0.057, 0.048, 0.039, 0.029, 0.02 , 0.011, 0.005]
    T: [0.132, 0.123, 0.113, 0.104, 0.095, 0.085, 0.076, 0.067, 0.057, 0.048, 0.039, 0.029, 0.02 , 0.011, 0.005]
    Q: [0.132, 0.123, 0.113, 0.104, 0.095, 0.085, 0.076, 0.067, 0.057, 0.048, 0.039, 0.029, 0.02 , 0.011, 0.005]
    SP: 0.1
    t2m: 1.0
    V500: 0.1
    U500: 0.1
    T500: 0.1
    Z500: 0.1
    Q500: 0.1
    
pbs:
  script_name: "gwm"
  select: "select:1:ncpus=32:ngpus=4:mem=480GB"
  walltime: "12:00:00"
  account: "NAML0001"
  queue: "main"
  out_path: "{save_loc}/out"
  err_path: "{save_loc}/out"
  bash: "module load conda; conda activate holodec"
  num_workers: 4
